// <auto-generated />
namespace MyBlog.Infrastructure.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class createdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201402170746065_createdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
